{

    "nodatafound": "Nema pronađeno prethodni podaci.",
    "retrievingdata": "Preuzimam ranije sačuvani podaci.",
    "datarestored": "Ranije sačuvani podaci su uspješno povrateni.",
    "greyuser": "Samo Bouncer i veci rank može pokrenuti i koristiti bot.",
    "bouncer": "Bot nemože pomicati ljude kada je koristen od strane Bouncera.",
    "online": "/me %%BOTNAME%% v%%VERSION%% je online!",


    "welcome": "/me Dobrodošli %%NAME%%",
    "welcomeback": "/me Dobrodošli nazad, %%NAME%%",
    "songknown": "/me :repeat: Ova pjesma je puštena %%PLAYS%% put(a) u zadnjih %%TIMETOTAL%%, zadnji put je bio %%LASTTIME%% :repeat:",
    "timelimit": "/me @%%NAME%%, vaša pjesma je duža od %%MAXLENGTH%% minuta, trebate dozvolu da puštate duže pjesme.",
    "permissionownsong": "/me :up: @%%NAME%% ima dozvolu da pušti svoji produkt!",
    "isblacklisted": "/me Ova pjesma je na %%BLACKLIST%% crna lista! Skipam...",


    "isopen": "/me Rulet je sad otvoren! Upišite !join da sudjelovate!",
    "winnerpicked": "/me Odabran je pobjednik! @%%NAME%% na pozicija %%POSITION%%.",


    "alreadyadding": "/me Korisnik je već dodan! Promijenjen željeni položaj na %%POSITION%%.",
    "adding": "/me @%%NAME%% je dodan(a) u redu. Trenutno mjesto: %%POSITION%%.",


    "usernotfound": "/me Korisnik nije pronađen.",
    "notdisconnected": "/me @%%NAME%% se nije diskonektovao dok sam ja bio tu..",
    "noposition": "/me Zadnja pozicija korisnika nije poznata. Waitlista se mora ažurirati barem jednom da se registrira pozicija korisnika.",
    "toolongago": "/me @%%NAME%% tvoji zadnji diskonekt (ili napuštanje) se desio pre: %%TIME%%.",
    "valid": "/me @%%NAME%% se diskonektovao pre %%TIME%% i treba biti na položaju %%POSITION%%.",


    "warning1": "/me @%%NAME%%, bili ste afk %%TIME%%, molim vas odgovorite u 2 minuta ili bićete uklonjeni od listu.",
    "warning2": "/me @%%NAME%%, bićete uskoro uklonjeni od listu ako ne napišete nešto.",
    "afkremove": "/me @%%NAME%%, odstranjeni ste zbog AFK %%TIME%%. Bili ste na poziciju %%POSITION%%. Odgovorite barem jednom svakih %%MAXIMUMAFK%% minuta ako želite da pustite pjesmu.


    "caps": "/me @%%NAME%%, nemojte pisati sa Caps Lockom molim vas.",
    "askskip": "/me @%%NAME%%, nemojte traziti skip.",
    "spam": "/me @%%NAME%%, molim vas ne spamajte.",
    "roomadvertising": "/me @%%NAME%%, nemojte reklamirati ostale plug.dj sobe molim vas.",
    "adfly": "/me @%%NAME%%, molim vas promjenite svoji AutoWoot progam. Mi predlažemo PlugCubed: http://plugcubed.net/",


    "invalidtime": "/me [@%%NAME%%] Neispravno vrijeme određeno.",
    "nouserspecified": "/me [@%%NAME%%] Nema određeno korisnika.",
    "invaliduserspecified": "/me [@%%NAME%%] Odredili ste nevažeći korisnik.",
    "nolistspecified": "/me [@%%NAME%%] Lista nije navedena.",
    "invalidlistspecified": "/me [@%%NAME%%] Naveli ste nevažeću listu.",
    "novaliduserspecified": "/me [@%%NAME%%] Važeći korisnik nije naveden.",
    "nolimitspecified": "/me [@%%NAME%%] Limit nije određen.",
    "invalidlimitspecified": "/me [@%%NAME%%] Navedeni limit ne važi.",
    "invalidpositionspecified": "/me [@%%NAME%%] Navedena pogrešna pozicija.",
    "toggleon": "/me [@%%NAME%%] %%FUNCTION%% omogućen(a).",
    "toggleoff": "/me [@%%NAME%%] %%FUNCTION%% onemogućen(a).",
    "afkremoval": "Odstranjivanje AFK osobe.",
    "afksremoved": "AFK osobe su odstranuti",
    "afklimit": "AFK limit",
    "autoskip": "autoskip",
    "newblacklisted": "/me [@%%NAME%%] Ova pjesma je na %%BLACKLIST%% crna lista! [ %%AUTHOR%% - %%TITLE%% - %%MID%% ]",
    "cycleguard": "cycleguard",
    "timeguard": "timeguard",
    "chatfilter": "chatfilter",
    "lockdown": "lockdown",
    "lockguard": "lockguard",
    "usercommands": "usercommands",
    "motd": "Nemojte zaboraviti da posjetite naši Minecraft server! IP: play.rebirthofbalkan.com",
    "welcomemsg": "Dobrodošli u oficijalni Rebirth of Balkan party soba! Nadamo se da ćete imati ljep provod!",
    "songstats": "song statistics",
    "etarestriction": "eta restriction",
    "voteskip": "voteskip",
    "voteskiplimit": "/me [@%%NAME%%] Limit za skipanje je %%LIMIT%% meh-ova.",
    "voteskipexceededlimit": "/me @%%NAME%%, vaša pjesma je prešla limit meh-ova: (%%LIMIT%% mehs).",
    "voteskipinvalidlimit": "/me [@%%NAME%%] Voteskip limit ne važi, pokušajte ponovo koristeći broj da označite broj meh-ova.",
    "voteskipsetlimit": "/me [@%%NAME%%] Voteskip limit postavljen na %%LIMIT%%.",
    "activeusersintime": "/me [@%%NAME%% Ukupno %%AMOUNT%% korisnike chatuju u zadnjih %%TIME%% minuta.",
    "maximumafktimeset": "/me [@%%NAME%%] Maximum AFK postavljeno na %%TIME%% minuta.",
    "afkstatusreset": "/me [@%%NAME%%] Resetiran afk status na @%%USERNAME%%.",
    "inactivefor": "/me [@%%NAME%%] @%%USERNAME%% je inaktivan već %%TIME%%.",
    "autowoot": "/me Preporučujemo PlugCubed za autowooting: http://plugcubed.net/",
    "brandambassador": "/me Brand Ambassador je glas plug.dj korisnika. Oni promoviraju nastane, usrećuju korisnike i reklamiraju plug.dj širom sveta. Za više informacije: http://blog.plug.dj/brand-ambassadors/",
    "bouncerplusrank": "/me [@%%NAME%%] Morate biti Manager da omogućite Bouncer+.",
    "chatcleared": "/me [@%%NAME%%] Je očistio chat.",
    "deletechat": "/me [@%%NAME%%] Je očistio chat od %%USERNAME%%.",
    "commandslink": "/me %%BOTNAME%% commands: http://goo.gl/rxNXKT",
    "eatcookie": "/me jede keks.",
    "nousercookie": "/em ne vidi %%NAME%% u sobi i jede keks.",
    "selfcookie": "/me @%%NAME%%, ti si malo pohlepan, zar ne? Daješ keks samog sebi, bah. Podijeli s ostalima!",
    "cookie": "/me @%%NAMETO%%, @%%NAMEFROM%% %%COOKIE%%",
    "cycleguardtime": "/me [@%%NAME%%] Cycleguard je podešen na %%TIME%% minuta.",
    "dclookuprank": "/me [@%%NAME%%] Samo Bouncer i iznad može napraviti pretraživanje za druge.",
    "emojilist": "/me Lista emotikona: %%http://www.emoji-cheat-sheet.com%%",
    "notinwaitlist": "/me @%%NAME%%, vi niste na wait listu.",
    "eta": "/me @%%NAME%% bićete na redu za otprilike %%TIME%%.",
    "facebook": "/me Like našu FB stranicu: %%https://www.facebook.com/robminecrafters?fref=ts%%",
    "starterhelp": "/me Ova slika pomoći će vam da započnete na plug.dj: http://i.imgur.com/SBAso1N.jpg",
    "roulettejoin": "/me @%%NAME%% je ušao na rulet! (!leave ako mislite da ćete zažaliti.)",
    "jointime": "/me [@%%NAMEFROM%%] @%%USERNAME%% je u sobi već %%TIME%%.",
    "kickrank": "/me [@%%NAME%%] ne možete kickati korisnike jednakim ili višeg ranka od sebe!",
    "kick": "/me [@%%NAME%%], @%%USERNAME%% kickani ste od sobu na %%TIME%% minuta.",
    "kill": "/me Gašenje.",
    "rouletteleave": "/me @%%NAME%% napustio rulet!",
    "songlink": "/me [@%%NAME%%] Link do sadašnju pjesmu: %%LINK%%",
    "usedlockskip": "/me [%%NAME%% used lockskip.]",
    "lockskippos": "/me [@%%NAME%%] Lockskip će premjestiti DJ-a na pozicija %%POSITION%%",
    "lockguardtime": "/me [@%%NAME%%] Lockguard je namješten na %%TIME%% minuta.",
    "maxlengthtime": "/me [@%%NAME%%] Maksimum dužina pjesama je sad %%TIME%% minuta.",
    "motdset": "/me MotD set to:  %%MSG%%",
    "motdintervalset": "/me MotD interval set to %%INTERVAL%%.",
    "addbotwaitlist": "/me @%%NAME%%, nemoj pokušavati me dodati na wait-list, molim te.",
    "move": "/me [%%NAME%% used move.]",
    "mutednotime": "/me [@%%NAME%%] Je mute @%%USERNAME%%.",
    "mutedmaxtime": "/me [@%%NAME%%] Možete mutati na maksimum %%TIME%% minuta.",
    "mutedtime": "/me [@%%NAME%%] Je mutao @%%USERNAME%% na %%TIME%% minuta.",
    "unmuted": "/me [@%%NAME%%] Je unmutao @%%USERNAME%%.",
    "muterank": "/me [@%%NAME%%] Ne možete mutati osobe s jednakim ili višeg ranka od sebe.",
    "oplist": "/me OP lista: %%http://goo.gl/%%",
    "pong": "/me Pong!",
    "reload": "/me Vraćam se odmah!",
    "removenotinwl": "/me [@%%NAME%%] Odabrani korisnik @%%USERNAME%% nije na wait-listu.",
    "roomrules": "/me Molim vas pročitajte pravila tu: http://goo.gl/3pjPxd",
    "sessionstats": "/me [@%%NAME%%] Ukupno woots: %%WOOTS%%, ukupno mehs: %%MEHS%%, ukupno grabs: %%GRABS%%.",
    "skip": "/me [%%NAME%% used skip.]",
    "madeby": "/me This bot was made by Mark Da Shark.",
    "activefor": "Ja sam aktivan već %%TIME%%.",
    "swapinvalid": "/me [@%%NAME%%] Navedeno nevažeći korisnik. (Nema imena s prostora!)",
    "swapwlonly": "/me [@%%NAME%%] Molim vas zamjenite korisnike koje su samo na wait listu!",
    "swapping": "/me Zamjenujem %%NAME1%% sa %%NAME2%%.",
    "genres": "/me Molimo procitajte dozvoljene zanrove za ovu sobu tu: http://goo.gl/gM7ahO",
    "notbanned": "/me [@%%NAME%%] Korisnik nije banovan.",
    "unmutedeveryone": "/me [@%%NAME%%] Unmutao svi u sobi.",
    "unmuteeveryonerank": "/me [@%%NAME%%] Samo Manager i iznad mogu unmutati svakog od jednom.",
    "notmuted": "/me [@%%NAME%%] taj korisnik nije bio mutan.",
    "unmuterank": "/me [@%%NAME%%] Ne možete unmutati korisnike s jednakim ili višim rankom od vas.",
    "commandscd": "/me [@%%NAME%%] Cooldown za korisnike je namješten na %%TIME%% sekunde.",
    "voteratio": "/me [@%%NAME%%] @%%USERNAME%% ~ woots: %%WOOT%%, mehs: %%MEHS%%, ratio (w/m): %%RATIO%%.",
    "website": "/me Molimo vas posjetite naši sajt: www.rebirthofbalkan.com",
    "youtube": "/me [%%NAME%%] Subscribe na naši YouTube kanal: LINK",
    "songstatistics": "/me %%ARTIST%% - %%TITLE%%: %%WOOTS%%W/%%GRABS%%G/%%MEHS%%M."
}
